version: '3.8'  # Use a more recent version

services:
  app:
    image: ghcr.io/dieechtemelly/scimatch:main
    container_name: scimatch
    build: .
    ports:
      - "8211:8501"
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always  # Ensure the container always restarts

